Closes #5 #11 - Improved how observers are configured and made scripts point to new fluo-stress repo

diff --git a/bin/fluo-dev b/bin/fluo-dev
--- a/bin/fluo-dev
+++ b/bin/fluo-dev
@@ -63,6 +63,14 @@ deploy)
 	;;
 stress)
   check_dirs
+  if [ -z "$STRESS_REPO" ]; then
+    echo "Error - STRESS_REPO is not set in env.sh"
+    exit 1
+  fi
+  if [ ! -d "$STRESS_REPO" ]; then
+    echo "Error - STRESS_REPO=$STRESS_REPO is not a valid directory."
+    exit 1
+  fi
   "$bin"/impl/stress.sh "${*:2}"
 	;;
 kill)
