Fixes #109 #112 - Add docs & checks for req sw
* Added documentation about required software and note that
  users should be able to SSH to localhost w/o a passhphrase
* Added checks for required software throughout code that
  aborts and prints error message if software is not found

diff --git a/bin/uno b/bin/uno
--- a/bin/uno
+++ b/bin/uno
@@ -43,6 +43,8 @@ function check_dirs() {
 
 case "$1" in
 fetch)
+  hash mvn 2>/dev/null || { echo >&2 "Maven must be installed & on PATH.  Aborting."; exit 1; }
+  hash wget 2>/dev/null || { echo >&2 "wget must be installed & on PATH.  Aborting."; exit 1; }
   if [[ "$2" == "all" ]]; then
     "$bin"/impl/fetch.sh accumulo
     "$bin"/impl/fetch.sh fluo
